# Generated by Django 4.2.7 on 2025-07-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockes',
            name='prix_vente',
        ),
        migrations.AddField(
            model_name='modificationstock',
            name='lot',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
