# Generated by Django 5.1.3 on 2025-04-02 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockes',
            name='date_ajout',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
