# Generated by Django 4.2.7 on 2025-07-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0002_remove_stockes_prix_vente_modificationstock_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='annule',
            field=models.BooleanField(default=False, verbose_name='Annulé'),
        ),
        migrations.AddField(
            model_name='vente',
            name='annule',
            field=models.BooleanField(default=False, verbose_name='Annulée'),
        ),
    ]
