# Generated by Django 5.1.3 on 2025-04-03 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0002_alter_stockes_date_ajout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockes',
            name='categorie',
        ),
        migrations.AddField(
            model_name='produits',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Produits.categories'),
        ),
    ]
