# Generated by Django 5.1.3 on 2025-04-03 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0003_remove_stockes_categorie_produits_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produits.categories'),
        ),
    ]
