# Generated by Django 4.2.7 on 2025-07-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0003_achat_annule_vente_annule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modificationstock',
            name='lot',
        ),
    ]
