# Generated by Django 5.1.3 on 2025-04-10 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0004_alter_produits_categorie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='vendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventes_effectuees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ModificationStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_modification', models.CharField(choices=[('ENTREE', 'Entrée en stock'), ('SORTIE', 'Sortie de stock'), ('AJUSTEMENT', "Ajustement d'inventaire")], max_length=10)),
                ('quantite', models.PositiveIntegerField()),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('raison', models.CharField(blank=True, max_length=255, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='Produits.stockes')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modifications_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modification de stock',
                'verbose_name_plural': 'Modifications de stock',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VIEW', 'Consultation')], max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('model_concerne', models.CharField(blank=True, max_length=50, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('date_activite', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité utilisateur',
                'verbose_name_plural': 'Activités utilisateurs',
                'ordering': ['-date_activite'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_utilisateur', models.CharField(choices=[('ADMIN', 'Administrateur'), ('MANAGER', 'Gestionnaire'), ('VENDEUR', 'Vendeur'), ('INVENTAIRE', "Gestionnaire d'inventaire")], default='VENDEUR', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
                'permissions': [('can_manage_inventory', "Peut gérer l'inventaire"), ('can_make_sales', 'Peut effectuer des ventes'), ('can_view_reports', 'Peut consulter les rapports'), ('can_manage_users', 'Peut gérer les utilisateurs')],
            },
        ),
    ]
