# Generated by Django 4.2.23 on 2025-07-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0004_remove_modificationstock_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockes',
            name='prix_achat',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
