# Generated by Django 5.1.3 on 2025-04-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0005_vente_vendeur_modificationstock_useractivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.CharField(max_length=250)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('mot_de_passe', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
