# Generated by Django 4.2.23 on 2025-08-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0005_stockes_prix_achat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achatligne',
            name='description',
        ),
    ]
