# Generated by Django 4.2.23 on 2025-08-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0006_remove_achatligne_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='statupaiement',
            field=models.CharField(choices=[('C', 'Cash'), ('D', 'Dette'), ('CH', 'Cheque'), ('OV', 'OV')], default='C', max_length=50),
        ),
    ]
