# Generated by Django 5.1.3 on 2025-04-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0006_utilisateur_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_creation',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
