# Generated by Django 4.2.23 on 2025-08-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0007_alter_vente_statupaiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('nif', models.CharField(max_length=100)),
                ('nc', models.CharField(max_length=100)),
                ('nom_tva', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('info_bancaire', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
        migrations.AddField(
            model_name='vente',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numéro de facture'),
        ),
    ]
