# Generated by Django 4.2.7 on 2025-05-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0007_alter_utilisateur_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='NIF',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
