# Generated by Django 4.2.7 on 2025-05-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0008_remove_customer_email_customer_nif'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockes',
            name='lot',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='date_payement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venteproduit',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
