# Generated by Django 4.2 on 2025-08-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0008_entreprise_vente_numero_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
