# Generated by Django 4.2.7 on 2025-05-21 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0009_stockes_lot_vente_date_payement_venteproduit_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='date_vente',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
