# Generated by Django 4.2.7 on 2025-09-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0009_produits_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='slug',
            field=models.SlugField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
