# Generated by Django 4.2.7 on 2025-09-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0010_alter_produits_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='statupaiement',
            field=models.CharField(choices=[('C', 'Cash'), ('D', 'Dette'), ('CH', 'Cheque'), ('P', 'Payer'), ('OV', 'OV')], default='C', max_length=50),
        ),
    ]
