# Generated by Django 4.2.7 on 2025-05-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0010_alter_vente_date_vente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venteproduit',
            old_name='prix',
            new_name='prix_vente',
        ),
    ]
