# Generated by Django 4.2.7 on 2025-09-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0011_alter_vente_statupaiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificationstock',
            name='motif',
            field=models.CharField(choices=[('ACHAT', 'Achat fournisseur'), ('RETOUR_CLIENT', 'Entrée - Retour client'), ('AJUSTEMENT_POSITIF', "Entrée - Ajustement d'inventaire"), ('ANNULATION_VENTE', 'Entrée - Annulation de vente'), ('VENTE', 'Vente client'), ('PERTE_PEREMPTION', 'Sortie - Perte (Péremption)'), ('PERTE_CASSE', 'Sortie - Perte (Casse)'), ('PERTE_VOL', 'Sortie - Perte (Vol)'), ('AJUSTEMENT_NEGATIF', "Sortie - Ajustement d'inventaire"), ('ANNULATION_ACHAT', "Sortie - Annulation d'achat")], default='VENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='modificationstock',
            name='raison',
            field=models.CharField(blank=True, help_text='Détails supplémentaires (ex: N° de vente/achat)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modificationstock',
            name='type_modification',
            field=models.CharField(choices=[('ENTREE', 'Entrée en stock'), ('SORTIE', 'Sortie de stock')], max_length=10),
        ),
    ]
