# Generated by Django 4.2.7 on 2025-05-31 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Produits', '0011_rename_prix_venteproduit_prix_vente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateTimeField(default=django.utils.timezone.now)),
                ('facture', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='stockes',
            old_name='condisionnement',
            new_name='conditionnement',
        ),
        migrations.AddField(
            model_name='stockes',
            name='prix_achat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockes',
            name='prix_vente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockes',
            name='stock_minimum',
            field=models.PositiveIntegerField(default=5, help_text='Quantité minimale avant alerte'),
        ),
        migrations.AlterField(
            model_name='stockes',
            name='date_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockes',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='venteproduit',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='Produits.vente'),
        ),
        migrations.AlterUniqueTogether(
            name='stockes',
            unique_together={('produit', 'lot', 'date_expiration')},
        ),
        migrations.CreateModel(
            name='AchatLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lot', models.CharField(blank=True, max_length=250, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='Produits.achat')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Produits.produits')),
            ],
        ),
        migrations.AddField(
            model_name='achat',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Produits.fournisseur'),
        ),
        migrations.AddField(
            model_name='achat',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='stockes',
            name='price',
        ),
        migrations.AddField(
            model_name='stockes',
            name='achat_ligne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Produits.achatligne'),
        ),
    ]
