# Generated by Django 4.2.7 on 2025-09-12 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0012_modificationstock_motif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modificationstock',
            name='quantite_apres',
            field=models.PositiveIntegerField(blank=True, help_text='Quantité en stock après la modification', null=True),
        ),
        migrations.AddField(
            model_name='modificationstock',
            name='quantite_avant',
            field=models.PositiveIntegerField(blank=True, help_text='Quantité en stock avant la modification', null=True),
        ),
        migrations.AddField(
            model_name='modificationstock',
            name='vente_ligne',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modification', to='Produits.venteproduit'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default=0, max_length=132),
            preserve_default=False,
        ),
    ]
