# Generated by Django 4.2.7 on 2025-06-03 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0012_achat_fournisseur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achatligne',
            options={'ordering': ['-date_ajout']},
        ),
        migrations.AlterModelOptions(
            name='stockes',
            options={'ordering': ['-achat_ligne__date_ajout'], 'verbose_name_plural': 'Stockes'},
        ),
        migrations.AddField(
            model_name='achatligne',
            name='conditionnement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Produits.condition'),
        ),
        migrations.AddField(
            model_name='achatligne',
            name='date_ajout',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='achatligne',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='stockes',
            unique_together={('produit', 'achat_ligne')},
        ),
        migrations.RemoveField(
            model_name='stockes',
            name='conditionnement',
        ),
        migrations.RemoveField(
            model_name='stockes',
            name='date_ajout',
        ),
        migrations.RemoveField(
            model_name='stockes',
            name='date_expiration',
        ),
        migrations.RemoveField(
            model_name='stockes',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stockes',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='stockes',
            name='prix_achat',
        ),
    ]
